### ISSUE TITLE
Mini drive-by code review

### ISSUE THREAD

**Issue by toolness** [noahmanger/calendar-cleanser#1]
Hi @noahmanger!  I wasn't sure where else to put this so I figured I'd just make an issue?

In [`background.js`](https://github.com/noahmanger/calendar-cleanser/blob/master/background.js#L18):

``` js
chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
  if (changeInfo.status == 'complete') {
    chrome.tabs.get(tabId, toggleExtension)
  }
})
```

You probably want to use `===` there I guess?

Also in `background.js`:

``` js
function toggleExtension(tab) {
  if (tab.url.includes('calendar.google.com')) {
    chrome.pageAction.show(tab.id);
    console.log(tab.id);
    chrome.tabs.executeScript(null, {
      file: 'content.js'
    })
```

You might want to explicitly pass `tab.id` as the first argument to `executeScript` there.  While it's very _likely_ that the tab that triggered `toggleExtension` is also the currently active tab, it might not be guaranteed.  A weird edge-case might involve a google calendar tab deciding to reload itself while in the background, maybe?

Also in `background.js`:

```
chrome.tabs.onActivated.addListener(function(activeInfo) {
  chrome.tabs.get(activeInfo.tabId, toggleExtension)
});
```

Er, does this actually mean that the `content.js` script will be injected multiple times if you were to e.g. press <kbd>alt</kbd>+<kbd>tab</kbd> a ton of times, "activating" the same Google Calendar tab and therefore calling `toggleExtension` on it several times?  I haven't written a Chrome extension in a while so I'm not sure...

In [`content.js`](https://github.com/noahmanger/calendar-cleanser/blob/master/content.js):

``` js
if (type === 'no') {
    check = calEvent.querySelector('.rsvp-no');
  } else if (type === 'maybe') {
    check = calEvent.querySelector('[title="Responded maybe"]');
  } else if (type === 'noRSVP') {
    check = calEvent.querySelector('[title="Not yet responded"]');
  }
```

Are there any selectors you can use that don't involve using English copy?  I assume not, which is fine--but if that's the case, you might want to mention in your add-on's description that it only works with the English localization of Google Calendar?

Anyhow, that's all I can think of right now, I hope it helps!

**Comment by noahmanger** [comment]
Thanks @toolness ! Made those fixes.

Unfortunately on the last point it doesn't seem to be possible.
